# Generated by Django 4.0.6 on 2022-07-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_order_alter_task_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
